INSERT INTO categories (name, name_pl) VALUES
    ('Groceries', 'Artykuły spożywcze'),
    ('Restaurants & Cafes', 'Restauracje i kawiarnie'),
    ('Transport', 'Transport'),
    ('Fuel', 'Paliwo'),
    ('Housing & Rent', 'Mieszkanie i czynsz'),
    ('Utilities', 'Opłaty i media'),
    ('Healthcare', 'Zdrowie'),
    ('Entertainment', 'Rozrywka'),
    ('Shopping', 'Zakupy'),
    ('Clothing', 'Odzież'),
    ('Electronics', 'Elektronika'),
    ('Education', 'Edukacja'),
    ('Subscriptions', 'Subskrypcje'),
    ('Insurance', 'Ubezpieczenia'),
    ('Transfers', 'Przelewy'),
    ('ATM Withdrawal', 'Wypłata z bankomatu'),
    ('Salary', 'Wynagrodzenie'),
    ('Freelance Income', 'Dochód z freelancingu'),
    ('Pubs & Bars', 'Puby i bary'),
    ('Fitness & Sport', 'Fitness i sport'),
    ('Personal Care', 'Higiena osobista'),
    ('Pets', 'Zwierzęta'),
    ('Gifts', 'Prezenty'),
    ('Travel', 'Podróże'),
    ('Other', 'Inne')
ON CONFLICT (name) DO NOTHING;
